// Auto-generated by download_sprites.py
// Import this in pokedraft.html: <script src='pokedraft-assets/manifest.js'></script>
const POKEMON_ASSETS = {
  Bulbasaur: {
    artwork:  'pokedraft-assets/artwork/1.png',
    front:    'pokedraft-assets/sprites/front/1.gif',
    back:     'pokedraft-assets/sprites/back/1.gif',
    icon:     'pokedraft-assets/icons/1.png',
  },
  Charmander: {
    artwork:  'pokedraft-assets/artwork/4.png',
    front:    'pokedraft-assets/sprites/front/4.gif',
    back:     'pokedraft-assets/sprites/back/4.gif',
    icon:     'pokedraft-assets/icons/4.png',
  },
  Squirtle: {
    artwork:  'pokedraft-assets/artwork/7.png',
    front:    'pokedraft-assets/sprites/front/7.gif',
    back:     'pokedraft-assets/sprites/back/7.gif',
    icon:     'pokedraft-assets/icons/7.png',
  },
  Pikachu: {
    artwork:  'pokedraft-assets/artwork/25.png',
    front:    'pokedraft-assets/sprites/front/25.gif',
    back:     'pokedraft-assets/sprites/back/25.gif',
    icon:     'pokedraft-assets/icons/25.png',
  },
  Geodude: {
    artwork:  'pokedraft-assets/artwork/74.png',
    front:    'pokedraft-assets/sprites/front/74.gif',
    back:     'pokedraft-assets/sprites/back/74.gif',
    icon:     'pokedraft-assets/icons/74.png',
  },
  Gastly: {
    artwork:  'pokedraft-assets/artwork/92.png',
    front:    'pokedraft-assets/sprites/front/92.gif',
    back:     'pokedraft-assets/sprites/back/92.gif',
    icon:     'pokedraft-assets/icons/92.png',
  },
  Machop: {
    artwork:  'pokedraft-assets/artwork/66.png',
    front:    'pokedraft-assets/sprites/front/66.gif',
    back:     'pokedraft-assets/sprites/back/66.gif',
    icon:     'pokedraft-assets/icons/66.png',
  },
  Abra: {
    artwork:  'pokedraft-assets/artwork/63.png',
    front:    'pokedraft-assets/sprites/front/63.gif',
    back:     'pokedraft-assets/sprites/back/63.gif',
    icon:     'pokedraft-assets/icons/63.png',
  },
  Magikarp: {
    artwork:  'pokedraft-assets/artwork/129.png',
    front:    'pokedraft-assets/sprites/front/129.gif',
    back:     'pokedraft-assets/sprites/back/129.gif',
    icon:     'pokedraft-assets/icons/129.png',
  },
  Eevee: {
    artwork:  'pokedraft-assets/artwork/133.png',
    front:    'pokedraft-assets/sprites/front/133.gif',
    back:     'pokedraft-assets/sprites/back/133.gif',
    icon:     'pokedraft-assets/icons/133.png',
  },
  Jigglypuff: {
    artwork:  'pokedraft-assets/artwork/39.png',
    front:    'pokedraft-assets/sprites/front/39.gif',
    back:     'pokedraft-assets/sprites/back/39.gif',
    icon:     'pokedraft-assets/icons/39.png',
  },
  Meowth: {
    artwork:  'pokedraft-assets/artwork/52.png',
    front:    'pokedraft-assets/sprites/front/52.gif',
    back:     'pokedraft-assets/sprites/back/52.gif',
    icon:     'pokedraft-assets/icons/52.png',
  },
  Psyduck: {
    artwork:  'pokedraft-assets/artwork/54.png',
    front:    'pokedraft-assets/sprites/front/54.gif',
    back:     'pokedraft-assets/sprites/back/54.gif',
    icon:     'pokedraft-assets/icons/54.png',
  },
  Slowpoke: {
    artwork:  'pokedraft-assets/artwork/79.png',
    front:    'pokedraft-assets/sprites/front/79.gif',
    back:     'pokedraft-assets/sprites/back/79.gif',
    icon:     'pokedraft-assets/icons/79.png',
  },
  Clefairy: {
    artwork:  'pokedraft-assets/artwork/35.png',
    front:    'pokedraft-assets/sprites/front/35.gif',
    back:     'pokedraft-assets/sprites/back/35.gif',
    icon:     'pokedraft-assets/icons/35.png',
  },
};